### ISSUE TITLE
Return 6-char masked url instead of ID

### ISSUE THREAD

**Issue by michellai** [nozbzh/urlshortener#5]
Figure out a good way to map unique DB ID to a 6-char key

**Comment by nozbzh** [comment]
I have a randomly generated 6 chars key.

Potential problem:
- it keeps generating a random key that already exists in the DB

**Comment by nozbzh** [comment]
fixed in 550257d8d17ade92cb95aadaf4f2022683e7c8d8

**Comment by kuanhsuh** [comment]
Question. In your routes you have   get "shortened/:short_url", to: "urls#shortened", as: :shortened
but I can't find shortened method in your controller? how does this work? Sorry I'm a beginner.

**Comment by nozbzh** [comment]
Hi @kuanhsuh 

Yes that's right, there is no action called #shortened in the controller. This is because Rails doesn't need us to explicitly define it unless we are doing something in the action (like defining an instance variable or redirecting for example). For simple apps, this is often the case for the #show action, where the only thing you do is fetch the record from the database and display it. Since this is usually done in a before filter, you don't need to define the #show action. As long as it is in the routes, Rails will find it.

I could have written this:

``` ruby
def shortened
end
```

but since there is no content I decided to remove it altogether.

Hope that makes sense to you.

**Comment by kuanhsuh** [comment]
ok thanks! one more question i notice you use redis in your gemfile, but I don't see anywhere that you use it. Am I missing something?

**Comment by nozbzh** [comment]
You're not missing anything, I just didn't delete redis from the gemfile. It's from a script I have that I use when I create a new app (it saves me from copying all the same gems and rewriting the templates in slim every time). I use redis with sidekiq for background jobs, but you're right, it is not used in this app.
